old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
        br:
            url: '%env(RABBITMQ_URL_BR)%'
    producers:
        test-producer:
            connection: default
            exchange_options: { name: 'testing-exchange', type: direct }
            class: App\RabbitMQ\Producer\TestProducer
    consumers:
        test:
            connection: default
            exchange_options: { name: 'testing-exchange', type: direct }
            queue_options: { name: 'testing-queue' }
            callback: App\RabbitMQ\Consumer\TestConsumer
        test_br:
            connection: br
            exchange_options: { name: 'testing-sap-exchange', type: direct }
            queue_options: { name: 'testing-sap-queue' }
            callback: App\RabbitMQ\Consumer\TestBrConsumer
