version: '3'
volumes:
    mysql_data:
services:
    microservice-sap-nginx-service:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        container_name: microservice-sap-nginx-container
        volumes:
            - ./../:/var/www/microservice-sap/
        ports: ['8106:80']
        networks:
            - microservice-sap-network
    microservice-sap-php-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: microservice-sap-php-container
        ports: ['9106:9000']
        volumes:
            - ./../:/var/www/microservice-sap/
            - ./../vendor:/var/www/microservice-sap/vendor
        networks:
            - microservice-sap-network
            - microservice-app-network
    microservice-sap-mysql-service:
        image: mysql
        container_name: microservice-sap-mysql-container
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--authentication_policy=mysql_native_password']
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports: ['3106:3306']
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - microservice-sap-network
    microservice-sap-phpmyadmin-service:
        image: phpmyadmin/phpmyadmin:latest
        container_name: microservice-sap-phpmyadmin-container
        environment:
            PMA_HOST: microservice-sap-mysql-service
            PMA_USER: root
            PMA_PASSWORD: root
        ports: ['7106:80']
        depends_on:
            - microservice-sap-mysql-service
        volumes:
            - ./phpmyadmin/:/var/www/microservice-sap/docker/phpmyadmin/
        networks:
            - microservice-sap-network
    microservice-bsap-rabbitmq-service:
        image: rabbitmq:3-management-alpine
        container_name: microservice-sap-rabbitmq-container
        ports: [ '5673:5672', '15673:15672' ]
        volumes:
            - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ./docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - microservice-sap-network
            - microservice-app-network
networks:
    microservice-sap-network:
        driver: bridge
    microservice-app-network:
        driver: bridge
        external: true
